/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.Carta;
import clases.Juego;
import clases.Jugador;
import clases.SimpleClient;
import clases.SimpleServer;
import clases.claseGeneral;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author Joshua
 */
public class frmChatPrevio extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form frmChatPrevio
     */
    public frmChatPrevio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEnviar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblNombreSala = new javax.swing.JLabel();
        cmdListo = new javax.swing.JButton();
        lblOponente = new javax.swing.JLabel();
        lblNombreOponente = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtChatPrevio = new javax.swing.JTextPane();

        setTitle("Chat Previo");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        txtEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnviarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre de la Sala:");

        lblNombreSala.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        cmdListo.setText("Listo");
        cmdListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdListoActionPerformed(evt);
            }
        });

        lblOponente.setText("Nombre del Servidor:");

        lblNombreOponente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jScrollPane2.setViewportView(txtChatPrevio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEnviar)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdListo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblOponente))
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombreOponente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombreSala, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOponente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombreOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 247, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdListo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        lblNombreSala.setText(claseGeneral.getNombreSala());
        if(claseGeneral.isSoyServer()){
            lblOponente.setText("Nombre del cliente:");
            lblNombreOponente.setText(claseGeneral.lstJugadores.get(1).getNombre());
            cmdListo.setEnabled(false);
        } else{
            lblOponente.setText("Nombre del servidor:");
            lblNombreOponente.setText(claseGeneral.lstJugadores.get(0).getNombre());
            cmdListo.setEnabled(true);
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnviarActionPerformed
        if(claseGeneral.isSoyServer()){
            SimpleServer.enviarDatos("CHP"+"0"+txtEnviar.getText());
        } else{
            SimpleClient.enviarDatos("CHP"+"1"+txtEnviar.getText());
        }
        
        SimpleAttributeSet attrs = new SimpleAttributeSet();
        StyleConstants.setBold(attrs, true);
        try {
            //El nombre primero en negrita
            txtChatPrevio.getStyledDocument().insertString(txtChatPrevio.getStyledDocument().getLength(),claseGeneral.getMiNombre()+" > ",attrs);
            StyleConstants.setBold(attrs, false);
            txtChatPrevio.getStyledDocument().insertString(txtChatPrevio.getStyledDocument().getLength(),txtEnviar.getText()+"\n",attrs);
        } catch (BadLocationException ex) {
            Logger.getLogger(claseGeneral.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtEnviar.setText("");
    }//GEN-LAST:event_txtEnviarActionPerformed

    private void cmdListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdListoActionPerformed
        if(claseGeneral.isSoyServer()){
            SimpleServer.enviarDatos("CHP0ready");
            
            List<Carta> lst6Cartas=new ArrayList();
            
            lst6Cartas = Juego.crearCartasRandom();
            
            claseGeneral.lstJugadores.get(0).setCartas(Juego.separarCartas(lst6Cartas,1));
            claseGeneral.lstJugadores.get(1).setCartas(Juego.separarCartas(lst6Cartas,2));
            
            Jugador j1 = (Jugador) claseGeneral.lstJugadores.get(1);
            Jugador j0 = (Jugador) claseGeneral.lstJugadores.get(0);
            
            SimpleServer.enviarDatos("JGOCCTS"+j1.cartasToString(j1.getCartas()));
            SimpleServer.enviarDatos("JGOSCTS"+j0.cartasToString(j0.getCartas()));
            
            claseGeneral.abrirJuego();
            claseGeneral.miJuego = new Juego();
        } else{
            try{
                SimpleClient.enviarDatos("CHP1ready");
                cmdListo.setEnabled(false);
                SimpleAttributeSet attrs = new SimpleAttributeSet();
                StyleConstants.setBold(attrs, true);
                txtChatPrevio.getStyledDocument().insertString(txtChatPrevio.getStyledDocument().getLength(),"Estas listo. Esperá al servidor.\n",attrs);
            } catch (BadLocationException ex) {
                Logger.getLogger(frmChatPrevio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmdListoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton cmdListo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNombreOponente;
    private javax.swing.JLabel lblNombreSala;
    private javax.swing.JLabel lblOponente;
    public static javax.swing.JTextPane txtChatPrevio;
    private javax.swing.JTextField txtEnviar;
    // End of variables declaration//GEN-END:variables
}
